import type { YamlObjectArray } from './yaml/yaml-schema';
export const yamlDatasetData: YamlObjectArray = [
  {
    MartName: 'Marketing',
    MartDescription: 'Marketing datasets',
    DatasetID: '6f755524-eee0-4394-acd1-0d881b26d0d9',
    DatasetName: 'Dataflow Input Datasources',
    DatasetDescription: 'What do you want',
    ColumnName: 'dimensions_stat_time_day',
    ColumnDescription: 'none',
    TestName: 'unique',
    TestParameter: 'none',
  },
  {
    MartName: 'Marketing',
    MartDescription: 'Marketing datasets',
    DatasetID: '6f755524-eee0-4394-acd1-0d881b26d0d9',
    DatasetName: 'Dataflow Input Datasources',
    DatasetDescription: 'What do you want',
    ColumnName: 'dimensions_stat_time_day',
    ColumnDescription: 'none',
    TestName: 'unique',
    TestParameter: 'none',
  },
  {
    MartName: 'Dentistry',
    MartDescription: 'Dentistry datasets',
    DatasetID: '6f524-eee0-4394-acd1-0d8fb26d0d9',
    DatasetName: 'Dataflow Input Datasources',
    DatasetDescription: 'What do you want',
    ColumnName: 'dimensions_stat_time_day',
    ColumnDescription: 'none',
    TestName: 'unique',
    TestParameter: 'none',
  },
  {
    MartName: 'Dentistry',
    MartDescription: 'Dentistry datasets',
    DatasetID: '6f524-eee0-4394-acd1-0d8fb26d0d9',
    DatasetName: 'Dataflow Input Datasources',
    DatasetDescription:'What do you want',
    ColumnName: 'dimensions_stat_time_day',
    ColumnDescription: 'none',
    TestName: 'freshness',
    TestParameter: '15',
  },
];
